name: Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker Image Name'
        required: true
      docker_tag:
        description: 'Docker Image Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }}

      - name: Save Docker image as tar file
        run: docker save -o image.tar ${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }}

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.docker_image }}-${{ github.event.inputs.docker_tag }}
          path: image.tar
