name: Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker Image Name'
        required: true
      docker_tag:
        description: 'Docker Image Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }}

      - name: Set filename
        id: set-filename
        run: |
          sanitized_image=$(echo "${{ github.event.inputs.docker_image }}" | sed 's|/|-|g')
          filename="${sanitized_image}-${{ github.event.inputs.docker_tag }}.tar"
          echo "filename=$filename" >> $GITHUB_ENV

      - name: Save Docker image as tar file
        run: docker save -o ${{env.filename}} ${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }}

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.filename}}
          path: ${{env.filename}}
